spring:
  datasource:
    url: jdbc:h2:mem:testparking;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true

logging:
  level:
    com.parking: DEBUG
